MIPS: tweak register constraint to build under clang
The constraints used for passing in the syscall number breaks when
building with clang:
.../lss/linux_syscall_support.h:2977:14: error: invalid input constraint '0' in asm
  LSS_INLINE _syscall1(void *,  brk,             void *,      e)
             ^

This might be a bug in clang itself, but we can tweak the constraints
on our side so it works with gcc & clang.

BUG=http://llvm.org/bugs/show_bug.cgi?id=21613
BUG=linux-syscall-support:9
TEST=gcc generates same asm before & after
TEST=clang now compiles
R=benchan@chromium.org

Review URL: https://codereview.chromium.org/836473006